In [1]:
# Python NUmpy

# Numerical Python
# Firstly we have Matlab for solving Problems and it has large functions and difficult to run
# Then Numpy came into existance 
# NumPy is a Python library.
# Numpy it is easy for calculation and which deals with arrays and Matrix

# TO IMPORT
->import numpy as np

In [2]:
# NUMPY

# 1.Vectors [ one row (or) one Column]
# 2.Matrix

In [1]:
import numpy as np
# simple array
l = [1,2,3,5]
arr = np.array(l)
arr

array([1, 2, 3, 5])

In [2]:
type(arr)

numpy.ndarray

In [3]:
np.asarray(l)

array([1, 2, 3, 5])

In [3]:
#Vectors
# Creating array

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
# Matrix
# 2D-NUMPY

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [42]:
arr.dtype

dtype('int32')

In [6]:
# version check
print(np.__version__)

1.18.5


In [9]:
# Know the NO of Dimention

print(arr.ndim)

2


In [4]:
two_d = np.array([[[1,2,3,4],[2,4,78,99],[3,4,6,8]]])

In [5]:
type(two_d)

numpy.ndarray

In [45]:
#range

list(range(5))

[0, 1, 2, 3, 4]

In [46]:
list(np.arange(1 , 10 ,2))

[1, 3, 5, 7, 9]

In [44]:

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
lily = [1,3,4,5]
d1 = np.matrix(lily)

In [12]:
type(d1)

numpy.matrix

In [19]:
#slicing

arr[0]
print(arr)

[1 2 3 5]


In [20]:
#Assigning Values
arr[0]=100
print(arr)

[100   2   3   5]


In [23]:
b = np.copy(arr)
print(b)

[100   2   3   5]


In [24]:
b[0]=200
print(b)

[200   2   3   5]


In [11]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [12]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [13]:
## ZEROS

In [15]:
np.zeros(3)   #1D

array([0., 0., 0.])

In [18]:
np.zeros((2,2)) #2D

array([[0., 0.],
       [0., 0.]])

In [19]:
np.zeros((3,3))  #3D

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
## ONES

In [21]:
np.ones(2)

array([1., 1.])

In [22]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [23]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [55]:
a1 = np.ones((3,3))
a1*3

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [58]:
#It create an array without initializing its values
np.empty((3,4))

array([[1.43107974e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.06099790e-312, 8.07598579e+169, 7.96526723e-042,
        4.08762701e-033],
       [2.78743930e+179, 5.26327597e-037, 5.75300221e-066,
        2.00528339e-076]])

In [24]:
## EYE

In [27]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Rando Rand

In [66]:
import pandas as pd
arr = np.eye(5)
print(arr)
print("\n")

print(pd.DataFrame(arr))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


     0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0


In [28]:
np.random.rand(3,3)

array([[0.63291517, 0.56026967, 0.99860753],
       [0.85917994, 0.11546137, 0.80623421],
       [0.04485692, 0.83659294, 0.51545117]])

In [29]:
np.random.randn(3)

array([ 0.61261017, -0.40130108,  0.97950849])

In [74]:
np.random.randint(3)

2

In [75]:
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [78]:
arr.reshape(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [5]:
# MAx
print(arr)
arr.max()

[1 2 3 4 5]


5

In [39]:
#size
arr.size

4

In [40]:
# Check the Shape

arr.shape

(4,)

In [ ]:
# Accessing Array 2-D

In [10]:
array2=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [14]:
# HOw can i access the first set of second number
print(array2[0,1])

2


In [15]:
# Accessing Array 3-D

In [16]:
array3=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [17]:
print(array3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [22]:
print(array3[0:1,2])

[3]


In [21]:
print(array3[1,2:5])

[ 8  9 10]


In [24]:
array4=np.array([[1,2],[3,4]])
print(array4[0:1])

[[1 2]]


In [25]:
print(array4[0:1])

[[1 2]]


In [4]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [29]:
# Slicing Array

In [31]:
arr_ =np.array([1,2,3,4,5,6,7])
arr_

array([1, 2, 3, 4, 5, 6, 7])

In [38]:
print(arr_[0])

1


In [39]:
# print  1 t0 4

print(arr_[0:4])

[1 2 3 4]


In [42]:
# print last two

print(arr_[-2:])

[6 7]


In [36]:
print(arr_[:-1])

[1 2 3 4 5 6]


In [37]:
print(arr_[::-1]) #reverse

[7 6 5 4 3 2 1]


In [43]:
print(arr_[4:])

[5 6 7]


In [44]:
# Iterative

In [45]:
arr_

array([1, 2, 3, 4, 5, 6, 7])

In [46]:
for i in arr_:
    print(i)

1
2
3
4
5
6
7


In [50]:
arr1_=np.array([[1,2,3,4],[4,5,6,7]])
arr1_

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [51]:
for i in arr1_:
    print(i)

[1 2 3 4]
[4 5 6 7]


In [52]:
# Sort

In [55]:
arr2_=np.array([[1,2,4,3],[8,6,5,7]])
arr2_

array([[1, 2, 4, 3],
       [8, 6, 5, 7]])

In [56]:
print(np.sort(arr2_))

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
# Identity

In [76]:
viis = np.identity(3)

In [77]:
viis

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [102]:
arra = np.arange(12,24).reshape(3,4)

In [103]:
arra

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [9]:
# Linespace - It is similar to the colon operator, “ : ”, but gives direct control over the number of points and always includes the endpoints. 

In [47]:
array1 = np.linspace(1,10,40) 

In [48]:
array1

array([ 1.        ,  1.23076923,  1.46153846,  1.69230769,  1.92307692,
        2.15384615,  2.38461538,  2.61538462,  2.84615385,  3.07692308,
        3.30769231,  3.53846154,  3.76923077,  4.        ,  4.23076923,
        4.46153846,  4.69230769,  4.92307692,  5.15384615,  5.38461538,
        5.61538462,  5.84615385,  6.07692308,  6.30769231,  6.53846154,
        6.76923077,  7.        ,  7.23076923,  7.46153846,  7.69230769,
        7.92307692,  8.15384615,  8.38461538,  8.61538462,  8.84615385,
        9.07692308,  9.30769231,  9.53846154,  9.76923077, 10.        ])

In [51]:

#logspace 
# np.logspace(start, stop, num=50, base=10)
np.logspace(1,10,base=2)

array([   2.        ,    2.27154434,    2.57995685,    2.9302432 ,
          3.32808868,    3.77995051,    4.2931626 ,    4.87605462,
          5.53808714,    6.29000526,    7.14401294,    8.1139711 ,
          9.21562258,   10.46684767,   11.88795431,   13.50200769,
         15.3352046 ,   17.41729864,   19.78208311,   22.4679395 ,
         25.51846045,   28.98315726,   32.91826347,   37.3876476 ,
         42.46384973,   48.22925884,   54.77745007,   62.21470345,
         70.66172888,   80.25562529,   91.15210586,  103.52802526,
        117.58425012,  133.54891916,  151.681146  ,  172.27522466,
        195.66540611,  222.2313233 ,  252.40415277,  286.67361283,
        325.59591193,  369.80277612,  420.01170228,  477.0376034 ,
        541.80603498,  615.3682172 ,  698.91809669,  793.81172479,
        901.5892669 , 1024.        ])

| Function        | Use When You Want...                                               |
| --------------- | ------------------------------------------------------------------ |
| `np.linspace()` | Linearly spaced numbers (equal intervals).                         |
| `np.logspace()` | Logarithmically spaced numbers (equal ratios, exponential growth). |



In [ ]:

# Copy the array 
array2 = np.array([1,2,3,4,5])
array4 = np.array([2,3,4,5,6])

In [12]:
array2

array([1, 2, 3, 4, 5])

In [13]:
array4

array([2, 3, 4, 5, 6])

In [14]:
array2 = np.copy(array4)

In [15]:
array2  #we can see that array4 data is copied to array2

array([2, 3, 4, 5, 6])

In [23]:
# SPLIT function 

# Split fuction which split the given function it to the given parts

In [19]:
myarray = np.array([1,2,3,4,5,5,6,7,8])

In [21]:
my_arraySplit = np.split(myarray,3)

In [22]:
my_arraySplit

[array([1, 2, 3]), array([4, 5, 5]), array([6, 7, 8])]

In [24]:
l = [1,2,3,4,5]

In [28]:
matrix_var =np.matrix(l)

In [29]:
matrix_var

matrix([[1, 2, 3, 4, 5]])

In [26]:
np.asanyarray(l)  #asanyarray : it is an function which convert any type of data into array

array([1, 2, 3, 4, 5])

In [30]:
np.asanyarray(matrix_var)
# Here matrix_var cannot able to convert the data into array because MATRIX is the sub set of ARRAY 

matrix([[1, 2, 3, 4, 5]])

In [31]:
# FromFUNCTION 

In [31]:
# It is used to generate the data 
# fromfunction 

f1_race = np.fromfunction(lambda i,j : i==j,(3,3))
f1_race

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [32]:
f11_race = np.fromfunction(lambda i,j :i*j,(3,3))
f11_race

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [34]:
np.fromfunction(lambda i,j: i==j ,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [37]:
np.fromfunction(lambda i,j: i*j ,(4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [38]:
list( i*i for i in range(5))

[0, 1, 4, 9, 16]

In [39]:
# Here by running loop and range function we get Squares

In [ ]:
# How can we get the same by using numpy 

In [43]:
sqrt_of = (i*i for i in range(5)) 

In [33]:
list(i* i for i in range(5))

[0, 1, 4, 9, 16]

In [34]:
sqt = (i*i for i in range(5))

In [35]:
sqtt  = np.fromiter(sqt,int)

In [36]:
sqtt

array([ 0,  1,  4,  9, 16])

In [41]:
np.fromiter(sqrt_of,int)

array([ 0,  1,  4,  9, 16])

In [44]:
np.fromiter(sqrt_of,float)

array([ 0.,  1.,  4.,  9., 16.])

In [45]:
# How to seperate string using Numpy

In [58]:
np.fromstring('23  45 67',sep=' ')

array([23., 45., 67.])

In [55]:
np.fromstring('23, 45, 67',sep=',')

array([23., 45., 67.])

In [59]:
# Maths functions in numpy

In [60]:
np.min([2,3,3,4,4,5])

2

In [61]:
np.max([2,3,5,55,66,7])

66

In [63]:
np.sqrt([1,4,25,64])

array([1., 2., 5., 8.])

In [64]:
np.square([2,3,3,4])

array([ 4,  9,  9, 16])

In [73]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10],[12,13,14,15,16]])

In [74]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16]])

In [ ]:
# Assignments 

same problem do for 

np.mean()
np.median()
np.power()
np.sin()
np.cos()
np.tan()
np.log10()
np.exp()

In [ ]:
# Array Manipulation

In [72]:
arr1.T  # Here T is Transpose

array([[ 1,  6, 12],
       [ 2,  7, 13],
       [ 3,  8, 14],
       [ 4,  9, 15],
       [ 5, 10, 16]])

In [76]:
arr1.flatten() # Flatten which convert the multiple array to single array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12, 13, 14, 15, 16])

In [77]:
data = [1,2,3,4] # It repeats the data

In [78]:
np.repeat(data,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [79]:
np.diag(data)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [5]:
data = np.array([[[1],[2],[3]]])
np.squeeze(data)

array([1, 2, 3])

In [6]:
np.roll(data,2)

array([[[2],
        [3],
        [1]]])

In [7]:
d1 = np.array(["Vishnu" , "kumar"])

In [8]:
np.char.upper(d1)

array(['VISHNU', 'KUMAR'], dtype='<U6')

In [9]:
np.char.capitalize(d1)

array(['Vishnu', 'Kumar'], dtype='<U6')

In [11]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10],[12,13,14,15,16]])

In [12]:
np.sort(arr1)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16]])

In [19]:
arr = np.array([ 2,  3,  4,  5,  8,  9, 12, 56])

In [20]:
np.where(arr > 0 )

(array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64),)

In [21]:
df = np.array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])
a = np.copy(df)

In [22]:
a

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [24]:
b=df.view()

In [25]:
b

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [26]:
b[3]

65