# 🎯 1. What Is Hyperparameter Tuning?

Hyperparameter tuning is about finding the best settings (hyperparameters) for a machine learning model — like:

- C, kernel in SVM

- n_estimators, max_depth in Random Forest

- learning_rate in XGBoost

These settings control how the model learns, but they’re not learned from the data — you set them manually or use tuning methods.

### 👉 Goal: Maximize model performance by trying different combinations.

### -  Hyperparameter Tuning Methods

| Method               | What it Does                                                                                |
| -------------------- | ------------------------------------------------------------------------------------------- |
| `GridSearchCV`       | Tries **all combinations** of hyperparameters exhaustively. Best when param space is small. |
| `RandomizedSearchCV` | Tries **random combinations** of hyperparameters. Faster when you have large search space.  |


# 🔍 2. What Is Cross-Validation (CV)?

Cross-validation is a technique to estimate the model’s true performance by:

- Splitting your training data into multiple "folds".

- Training and testing on different combinations of these folds.

- Averaging the results to get a reliable performance estimate.

### 👉 Goal: Avoid overfitting and get a better idea of how the model performs on unseen data.

### -  Common Cross-Validation Strategies


| Method            | Description                                                                        |
| ----------------- | ---------------------------------------------------------------------------------- |
| `KFold`           | Splits data into k equal folds (e.g. 5 or 10). Each fold gets to be the test once. |
| `StratifiedKFold` | Same as KFold, but keeps label distribution balanced (good for classification).    |
| `ShuffleSplit`    | Randomly shuffles and splits the data into train/test multiple times.              |
| `LeaveOneOut`     | One sample is test, rest train. Repeated for all samples. Very slow.               |


| Aspect                | Hyperparameter Tuning                                          | Cross-Validation                                    |
| --------------------- | -------------------------------------------------------------- | --------------------------------------------------- |
| **Purpose**           | Find best hyperparameter settings                              | Estimate model performance                          |
| **Focus**             | Model configuration                                            | Model evaluation                                    |
| **Is it required?**   | Optional but improves accuracy                                 | Highly recommended                                  |
| **Example tool**      | `GridSearchCV`, `RandomizedSearchCV`                           | `KFold`, `StratifiedKFold`                          |
| **How they interact** | Hyperparameter tuning *uses* CV to evaluate each parameter set | CV does not tune hyperparameters, it just validates |


In [97]:
# HANDS ON 
import seaborn as sns
from sklearn.datasets import load_breast_cancer
import numpy as np
import pandas as pd

In [98]:
data = load_breast_cancer()

In [99]:
df = pd.DataFrame(data.data,columns=data.feature_names)

In [100]:
df['target'] = data.target

In [101]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

In [102]:
X = df.drop(['target'],axis=1)

In [103]:
y = df['target']

In [104]:
X_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [105]:
scaler = StandardScaler()

In [106]:
X_traine_scaled= scaler.fit_transform(X_train)

In [107]:
X_test_scaled = scaler.transform(X_test)

In [108]:
lg = LogisticRegression(max_iter=1000)

In [109]:
lg.fit(X_traine_scaled,y_train)

LogisticRegression(max_iter=1000)

In [110]:
y_pred = lg.predict(X_test)

In [111]:
X_test.shape

(114, 30)

In [112]:
y_pred.shape

(114,)

## GridSearchCV

In [113]:
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')

In [114]:
parameters={'penalty':('l1', 'l2','elasticnet'),'C':[1,10,20,30]}

In [115]:
clf=GridSearchCV(lg,param_grid=parameters,cv=5)

In [116]:
## Splitting of Training data to train and validation
clf.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(max_iter=1000),
             param_grid={'C': [1, 10, 20, 30],
                         'penalty': ('l1', 'l2', 'elasticnet')})

In [117]:
clf.best_params_

{'C': 10, 'penalty': 'l2'}

In [118]:
clf.best_score_

0.9626373626373628

In [119]:
classifier=LogisticRegression(C=1,penalty='l2')

In [120]:
classifier.fit(X_train,y_train)

LogisticRegression(C=1)

In [121]:
y_pred=classifier.predict(X_test)

In [122]:
y_pred

array([0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1])

In [123]:
classifier.predict_proba(X_test)

array([[9.86669631e-01, 1.33303694e-02],
       [9.99999999e-01, 8.18325705e-10],
       [1.17431950e-02, 9.88256805e-01],
       [6.15098684e-01, 3.84901316e-01],
       [3.77607040e-03, 9.96223930e-01],
       [1.00000000e+00, 1.18044518e-13],
       [3.88082106e-02, 9.61191789e-01],
       [2.51985506e-02, 9.74801449e-01],
       [2.20183742e-03, 9.97798163e-01],
       [1.82478622e-02, 9.81752138e-01],
       [9.99999908e-01, 9.15683452e-08],
       [9.87023841e-01, 1.29761595e-02],
       [3.36287661e-01, 6.63712339e-01],
       [9.99999999e-01, 7.56570701e-10],
       [9.99984818e-01, 1.51822582e-05],
       [1.00000000e+00, 8.75090173e-25],
       [6.05228786e-02, 9.39477121e-01],
       [1.53359595e-01, 8.46640405e-01],
       [1.20429268e-02, 9.87957073e-01],
       [4.97993314e-03, 9.95020067e-01],
       [8.79820869e-01, 1.20179131e-01],
       [9.37968761e-04, 9.99062031e-01],
       [6.60691926e-03, 9.93393081e-01],
       [2.60512635e-02, 9.73948736e-01],
       [7.356670

In [124]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [125]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[16 27]
 [25 46]]
0.543859649122807
              precision    recall  f1-score   support

           0       0.39      0.37      0.38        43
           1       0.63      0.65      0.64        71

    accuracy                           0.54       114
   macro avg       0.51      0.51      0.51       114
weighted avg       0.54      0.54      0.54       114



## Randomized Search cv

In [127]:
from sklearn.model_selection import RandomizedSearchCV

In [128]:
random_clf=RandomizedSearchCV(LogisticRegression(),param_distributions=parameters,cv=5,n_iter=20)

In [129]:
random_clf

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_iter=20,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'penalty': ('l1', 'l2', 'elasticnet')})

In [130]:
random_clf.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_iter=20,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'penalty': ('l1', 'l2', 'elasticnet')})

In [131]:
random_clf.best_params_

{'penalty': 'l2', 'C': 20}

# Conclusion:
The best model uses L2 regularization with moderate strength (C=1), indicating a balanced trade-off between bias and variance.

| Metric    | Focus                       | Best For                    | Formula                         |
| --------- | --------------------------- | --------------------------- | ------------------------------- |
| Accuracy  | Overall correctness         | Balanced data               | (TP + TN) / (TP + TN + FP + FN) |
| Precision | Positive prediction quality | False positive concern      | TP / (TP + FP)                  |
| Recall    | Finding all positives       | False negative concern      | TP / (TP + FN)                  |
| F1 Score  | Balance precision & recall  | Imbalanced data             | 2 \* (P \* R) / (P + R)         |
| Fβ Score  | Weighted F1 Score           | Precision or recall focused | (1+β²)(P×R) / (β²×P + R)        |
| ROC Curve | Visual performance          | Binary classifiers          | Plot TPR vs. FPR                |
| AUC       | Summary of ROC              | Imbalanced data             | Area under the ROC curve        |
